### ISSUE TITLE
Song ID 221 is corrupted

### ISSUE THREAD

**Issue by celunah** [AllenSeitz/dance-maniax-update#5]
Song ID 221 "Buffalo Bill |(Momo Re-Edit)" is corrupted and weighs 0 bytes.
It cannot be played in the game due to this.

**Comment by AllenSeitz** [comment]
That song doesn't exist. It was cut from the original Dance Maniax 2nd Mix and it was "0 bytes" in the official game too. Since my song ids follow the same order as the official ones I skipped id 221 as well.

Just this year someone finally dumped the chart data for all of Dance Maniax. While a few unused charts were found, none of them were for this song. So it'll never be in the game.
